- block:
   - include: instantiate_vm.yml
   - include: allocate_floating_ip.yml
  when: mode=="create"

- block:
   - include: set_floating_ip_as_fact.yml
   - name: wait for vm to become available
     local_action: wait_for host={{ ansible_host }} port=22 timeout=600
   - name: wait for subscription to finish
     shell: subscription-manager status | awk '/^Overall Status/{ print $3 }'
     register: subscription_status
     until: subscription_status.stdout == 'Current' or subscription_status.stdout == 'Insufficient'
     failed_when: subscription_status.stdout == ''
     changed_when: false
     retries: 30
     delay: 20
  when: mode=="create" or mode=="readfacts"

- block:
    - include: set_floating_ip_as_fact.yml
    - include: remove_floating_ip.yml
    - include: terminate_vm.yml
  when: mode=="destroy"


- set_fact:
    vm_exists: true
    #TODO - create a "start" mode which starts the VM and sets this fact
