- name: subscribe RHEL
  redhat_subscription: state=present username={{ rhsm_username }} password={{ rhsm_password }} pool={{ poolid }}
- name: attach to pool
  command: 'subscription-manager attach --pool={{ poolid }}'
- name: enable repos
  command: 'subscription-manager repos --disable="*"
                                       --enable="rhel-7-server-rpms"
                                       --enable="rhel-7-server-extras-rpms"
                                       --enable="rhel-7-server-ose-3.1-rpms"'
- name: upgrade packages
  yum: name=* state=latest
- name: install all prerequisites
  yum: name=wget,git,net-tools,bind-utils,iptables-services,bridge-utils,bash-completion,atomic-openshift-utils,docker state=latest
  notify:
    - reboot server
    - waiting for server to come back
