---

# - name: add binduser to IPA for rhev
#   ipa: args="user-add rhev-bind-user --first=rhev --last=binduser"
#     password="{{ ipa_admin_password }}"
#     ignore_no_modifications=true
#
# - name: add abradshaw to IPA
#   ipa: args="user-add abradshaw --first=adrian --last=bradshaw"
#     password="{{ ipa_admin_password }}"
#     ignore_no_modifications=true

- name: find existing users
  shell: echo "{{ ipa_admin_password }}" | kinit admin && ipa user-find | grep "User login:" | cut -c 15-
  register: users

- name: add users to IPA
  shell: echo "{{ ipa_admin_password }}" | kinit admin && ipa user-add "{{ item.name }}" --first="{{ item.first }}" --last="{{ item.last }}"
  when: item.name not in users.stdout_lines
  with_items: "{{ ipa_user }}"

- name: set initial password for users
  shell: echo -e "{{ ipa_admin_password }}\ndummy4711\ndummy4711 | (kinit admin && ipa user-mod {{ item.name }} --password)"
  when: item.name not in users.stdout_lines
  with_items: "{{ ipa_user }}"

- name: login as user and change password
  shell: echo -e "dummy4711\n{{ item.password }}\n{{ item.password }} | kinit {{ item.name }}"
  when: item.name not in users.stdout_lines and item.password is defined
  with_items: "{{ ipa_user }}"
