- block:
    - include: ipa-firewalld.yml
    - include: ipa-rng-service.yml
    - include: ipa-ntp-service.yml
    - include: ipa-configure.yml
    - include: ipa-dns-records-add.yml
    - include: ipa-users-add.yml 
  when: mode=="create"
