- block:
    - include: ipa-firewalld.yml
      tags: ['ipa-install']
    - include: ipa-rng-service.yml
      tags: ['ipa-install']
    - include: ipa-ntp-service.yml
      tags: ['ipa-install']
    - include: ipa-configure.yml
      tags: ['ipa-install']
    - include: ipa-dns-records-add.yml
    - include: ipa-users-add.yml
  when: mode=="create"
