- name: get network id
  shell: curl -XGET {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         "https://{{ hostvars['rhevm'].nic[1].ip }}/api/networks" | \
         xmllint --xpath "//networks/network[name='{{ item.network }}']/@id" - | \
         awk 'match($0, /.*="(.*)"/, m) { print m[1]  }'
  changed_when: false
  failed_when: network_id.stdout == ''
  register: network_id
  when: unassigned_nic.stdout.find(item.dev) != -1

- debug: var=network_id

- name: get networkattachment links
  shell: curl -XGET {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         "https://{{ hostvars['rhevm'].nic[1].ip }}{{ host_nics_url.stdout }}" | \
         xmllint --xpath "//host_nics/host_nic[name='{{ item.dev }}']/link[@rel='networkattachments']/@href" - | \
         awk 'match($0, /.*="(.*)"/, m) { print m[1]  }'
  changed_when: false
  failed_when: networkattachment_url.stdout == ''
  register: networkattachment_url
  when: not network_id|skipped

- name: get deactivate host link
  shell: curl -XGET {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         "https://{{ hostvars['rhevm'].nic[1].ip }}/api/hosts" | \
         xmllint --xpath "//host[name='{{ hostname }}']/actions/link[@rel='deactivate']/@href" - | \
         awk 'match($0, /.*="(.*)"/, m) { print m[1]  }'
  changed_when: false
  failed_when: deactivate_url.stdout == ''
  register: deactivate_url
- name: set host into maintenance mode (deactivate host)
  shell: curl -XPOST {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         -d '<action />'
         "https://{{ hostvars['rhevm'].nic[1].ip }}{{ deactivate_url.stdout }}"

- name: attach nics to networks
  shell: curl -XPOST {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         -d '{{ lookup('template','nic_network_attachment1.xml.j2') }}'
         "https://{{ hostvars['rhevm'].nic[1].ip }}{{ networkattachment_url.stdout }}"
  register: res
  when:  not networkattachment_url|skipped
- debug: var=res


- name: get activate host link
  shell: curl -XGET {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         "https://{{ hostvars['rhevm'].nic[1].ip }}/api/hosts" | \
         xmllint --xpath "//host[name='{{ hostname }}']/actions/link[@rel='activate']/@href" - | \
         awk 'match($0, /.*="(.*)"/, m) { print m[1]  }'
  changed_when: false
  failed_when: activate_url.stdout == ''
  register: activate_url
- name: set host into active mode (activate host)
  shell: curl -XPOST {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         -d '<action />'
         "https://{{ hostvars['rhevm'].nic[1].ip }}{{ activate_url.stdout }}"
