- name: get host nics link
  shell: curl -XGET {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         "https://{{ hostvars['rhevm'].nic[0].ip }}/api/hosts" | \
         xmllint --xpath "//host[name='{{ hostname }}']/link[@rel='nics']/@href" - | \
         awk 'match($0, /.*="(.*)"/, m) { print m[1]  }'
  changed_when: false
  failed_when: host_nics_url.stdout == ''
  register: host_nics_url

- name: get network ids
  shell: curl -XGET {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         "https://{{ hostvars['rhevm'].nic[0].ip }}/api/networks" | \
         xmllint --xpath "//networks/network[name='{{ item.network }}']/@id" - | \
         awk 'match($0, /.*="(.*)"/, m) { print m[1]  }'
  changed_when: false
  failed_when: network_ids.stdout == ''
  register: network_ids
  with_items: "{{ nic }}"

- name: get nic links
  shell: curl -XGET {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         "https://{{ hostvars['rhevm'].nic[0].ip }}{{ host_nics_url.stdout }}" | \
         xmllint --xpath "//host_nics/host_nic[name='{{ item.item.dev }}']/link[@rel='networkattachments']/@href" - | \
         awk 'match($0, /.*="(.*)"/, m) { print m[1]  }'
  changed_when: false
  failed_when: nic_url.stdout == ''
  register: nic_url
  with_items: "{{ network_ids.results }}"

- name: attach nics to networks
  shell: curl -XPOST {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
         -d '<network_attachment><network id="{{ item.item.stdout }}" /></network_attachment>'
         "https://{{ hostvars['rhevm'].nic[0].ip }}{{ item.stdout }}"
  with_items: "{{ nic_url.results }}"
  register: res
- debug: var=res

# - name: get list of nic ids
#   shell: curl -XGET {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
#          "https://{{ nic[0].ip }}{{ host_nics_url.stdout }}" | \
#          xmllint --xpath "//host_nics/host_nic/[name='{{ item.dev }}']/@id" - \
#          awk 'match($0, /.*="(.*)"/, m) { print m[1]  }'
#   register: nic_id
#   changed_when: false
#   failed_when: nic_id.stdout == ''
#   with_items: "{{ nic }}"
#
# - debug: var=nic_id
#
# - name: get list of network ids

# - name: attach nics to networks
#   shell: curl -XPOST {{ lookup('template','../common/templates/rhev_curl_xml_params.j2') | trim }} \
#          -d '<network_attachment><network><name>{{ item.network }}</name></network><host_nic><name>{{ item.dev }}</name></host_nic></network_attachment>'
#          "https://{{ hostvars['rhevm'].nic[0].ip }}{{ host_nics_url.stdout }}"
#   with_items: "{{ nic }}"
#   register: res
# - debug: var=res
