- name: ensure interface is in the correct firewall zone
  command: firewall-cmd --zone={{ dnat_rules.firewall_zone }} --change-interface={{ dnat_rules.layer1_dev }}

- name: check IP address on DNAT interfaces
  command: ip addr show dev {{ dnat_rules.layer1_dev }} | awk '/inet / { print $2 }'
  register: device_ip_addresses
  changed_when: false

- name: assign IP address if necessary
  command: ipp addr add {{ item.from_host_prefix }} dev eth0
  when: item.from_host_prefix not in device.ip.addresses.stdout_lines
  with_items: {{ dnat_rules.rules }}

- name: check DNAT forwarding rules
  command: firewall-cmd --permanent --zone={{ item.0.firewall_zone }} {{ item.1.from }}:proto={{ item.1.proto }}:toport={{ item.1.to }}:toaddr={{ item.0.to_ip -}}

- name: add DNAT forwarding rule if necessary
- name: trigger firewall reload
  command: firewall-cmd --reload
