# copy rhel kvm base image to host
#- name: copy rhel kvm base image
#  copy:  src=../binary/{{ rhel_kvm_img }} dest={{ layer1_qcow_storage.path }}/{{ rhel_kvm_img }} mode=0644

# copy rhel isoimage to host
- name: copy rhel iso image
  copy:  src=../binary/{{ item }} dest={{ layer1_qcow_storage.path }}/{{ item }} mode=0644
  with_items:
    - "{{ rhel7_iso_img }}"
    - "{{ rhel6_iso_img }}"
  when: layer1_binary_dir is not defined

#TODO WR: some issue seems to prevent delegate_to and with_items to work together - I always get the message that hostvars is not defined in that case
# - block:
#   - name: locally copy rhel6 iso image
#     synchronize: mode=pull src={{ layer1_binary_dir }}/{{ rhel6_iso_img }} dest={{ layer1_qcow_storage.path }}/{{ rhel6_iso_img }}
#     delegate_to: "{{ infrastructure_delegate_local_content_host }}"
#   - name: locally copy rhel7 iso image
#     synchronize: mode=pull src={{ layer1_binary_dir }}/{{ rhel7_iso_img }} dest={{ layer1_qcow_storage.path }}/{{ rhel7_iso_img }}
#     delegate_to: "{{ infrastructure_delegate_local_content_host }}"
#   when: layer1_binary_dir is defined

- name: locally copy rhel iso image
  synchronize: mode=pull src={{ layer1_binary_dir }}/{{ item }} dest={{ layer1_qcow_storage.path }}/{{ item }}
  delegate_to: "{{ infrastructure_delegate_local_content_host }}"
  with_items:
    - "{{ rhel6_iso_img }}"
    - "{{ rhel7_iso_img }}"
  when: layer1_binary_dir is defined
