# define storage pool
- name: ensure image directory is present
  file: state=directory path={{ storage_default.path }}
- name: define storage pool
  virt_pool: uri=qemu:///system name={{ item.name }} command=define xml='{{ lookup("template", "libvirt_pool.xml.j2") }}'
  with_items:
    - "{{ storage_default }}"
- name: start storage
  virt_pool: uri=qemu:///system name={{ item.name }} state=active
  with_items:
    - "{{ storage_default }}"
- name: autostart storage pool
  virt_pool: uri=qemu:///system name={{ item.name }} autostart=yes
  with_items:
    - "{{ storage_default }}"
