- name: start rpcbind
  service: name=rpcbind state=started enabled=yes
- name: start nfs-server
  service: name=nfs-server state=started enabled=yes
- name: open firewall for nfs-server on internal zone
  firewalld: port=2049/tcp permanent=true state=enabled zone=internal
- name: open firewall for rpc-bind on internal zone
  firewalld: service=rpc-bind permanent=true immediate=true state=enabled zone=internal
