- name: get current connections
  shell: nmcli con show | cut -c68- | awk '{ print $1 }'
  register: current_connections
  changed_when: false

# - name: deactivate bridge
#   command: nmcli con down {{ infrastructure_network_guests.bridge }}
#   when: >
#     infrastructure_network_guests.forward_mode == "bridge"
#     and
#     infrastructure_network_guests.bridge not in current_connections.stdout_lines
#
# - name: create bridge
#   shell: nmcli con delete {{ infrastructure_network_guests.bridge }}
#   when: >
#     infrastructure_network_guests.forward_mode == "bridge"
#     and
#     infrastructure_network_guests.bridge not in current_connections.stdout_lines
