- name: create /etc/hailstorm_iptables.xml
  template: src=hailstorm_iptables.xml.j2 dest=/etc/hailstorm_iptables.xml
  register: iptables
- name: restart networks
  shell: virsh net-destroy {{ item.netname }} && virsh net-start {{ item.netname }}
  when: iptables|changed
  with_items: "{{ infrastructure_networks }}"
