---
mem: "{{ layer2_ose3lb_mem }}"
vcpu: "{{ layer2_ose3lb_cpu }}"

disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 2048
    home: 2048
    root: 10000


scl_packages:
  - rh-maven33
  - rh-nodejs4

repos: "{{ ose3_repos + ['rhel-server-rhscl-7-rpms'] }}"
packages: "git,bash-completion,atomic-openshift-clients,ipa-client,{{ scl_packages | join(',') }}"
pool_regex: "{{ ose_subscription_pool_regex }}"
