---
name: ipa
mem: 2048
vcpu: 2
disk:
  path: ipa.qcow2
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 2048
    home: 2048
    root: 10000
nic:
  - ip: 192.168.100.23
    dev: eth0
    network: default
    default_route: true
  - ip: 192.168.103.23
    dev: eth1
    network: admin
    default_route: false
#hostname is now set in group_vars/all.yml
#hostname: ipa.example.com
#root_password is now set in config/hailstorm_config.yml
#root_password: redhat01
ansible_host: 192.168.103.23

ntp_client: ntp

#poolid: 8a85f9843e3d687a013e3ddd471a083e
repos: "{{ ipa_repos }}"
packages: ipa-server,ipa-server-dns,rng-tools

ipa_admin_password: "{{ root_password }}"

firewalld_rules:
 - DNStcp:
   port: 53
   protocol: udp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - DNSudp:
   port: 53
   protocol: udp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - HTTPtcp:
   port: 80
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - LDAPtcp:
   port: 389
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - HTTPStcp:
   port: 443
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - LDAPStcp:
   port: 636
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - KRB1tcp:
   port: 88
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - KRB2tcp:
   port: 464
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - KRB1udp:
   port: 88
   protocol: udp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - KRB2udp:
   port: 464
   protocol: udp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - NTPudp:
   port: 123
   protocol: udp
   state: enabled
   zone: public
   permanent: true
   immediate: true
