# ip address or host name of layer1 system
#ansible_host: inf43.coe.muc.redhat.com
ansible_host: "{{ layer1_ansible_host }}"
ansible_ssh_common_args: "-i ./binary/hailstorm"

network_default:
  name: 'default'
  bridge: 'virbr0'
  forward_mode: 'nat'
  host_prefix: 192.168.100.1/24
  dhcp_start: 192.168.100.128
  dhcp_end: 192.168.100.172
  floating_start: 192.168.100.173
  floating_end: 192.168.100.254

network_rhosp_provisioning:
  name: 'rhosp_provisioning'
  bridge: 'virbr1'
  forward_mode: 'nat'
  host_prefix: 192.168.101.1/24

network_storage:
  name: 'storage'
  bridge: 'virbr2'
  host_prefix: 192.168.102.1/24

network_admin:
  name: 'admin'
  bridge: 'virbr3'
  host_prefix: 192.168.103.1/24
  dhcp_start: 192.168.103.173
  dhcp_end: 192.168.103.254

network_rhosp_internal:
  name: 'rhosp_internal'
  bridge: 'virbr4'
  host_prefix: 192.168.104.1/24

networks:
  - "{{ network_default }}"
  - "{{ network_rhosp_provisioning }}"
  - "{{ network_storage }}"
  - "{{ network_admin }}"
  - "{{ network_rhosp_internal }}"

#kickstart_path: /srv/kickstart
kickstart_path: "{{ layer1_kickstart_folder }}"
