---
mem: 4096
vcpu: 2
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2
  # partition_table:
  #   lvmpv: 29500
  #   swap: 2048
  #   home: 2048
  #   root: 10000
  physvols:
    boot: 500
    rhel: 29500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 10000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048
    - name: var
      fstype: "{{ fstype }}"
      mountpoint: /var
      size: 12000


repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - jb-eap-7.0-for-rhel-7-server-rpms
  - rh-sso-7.1-for-rhel-7-server-rpms

#  "{{ rh_sso_repos }}"