---
name: rhevh1

nic:
  - ip: 192.168.100.11
    dev: eth0
    network: default
    default_route: true
  - ip: 192.168.103.11
    dev: eth1
    network: admin
    default_route: false
ksdevice: eth1
hostname: rhevh1.example.com
root_password: redhat01
#graphics: vnc,listen=0.0.0.0,password=redhat01

ansible_host: 192.168.103.11
