---
name: rhevm
mem: 4096
vcpu: 2
disk:
  path: rhevm.qcow2
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 2048
    home: 2048
    root: 10000
nic:
  - ip: 192.168.100.10
    dev: eth0
    network: default
    default_route: true
  - ip: 192.168.103.10
    dev: eth1
    network: admin
    default_route: false
hostname: rhevm.example.com
root_password: redhat01
ansible_host: 192.168.103.10

poolid: 8a85f9843e3d687a013e3ddd46dd07f1

repos:
  - rhel-6-server-rpms
  - rhel-6-server-supplementary-rpms
  - rhel-6-server-rhevm-3.6-rpms
  - jb-eap-6-for-rhel-6-server-rpms
packages: rhevm

