---
name: rhevh2

nic:
  - ip: 192.168.100.12
    dev: eth0
    network: default
    default_route: true
  - ip: 192.168.103.12
    dev: eth1
    network: admin
    default_route: false
ksdevice: eth1
#hostname: rhevh2.example.com
#hostname is now set in group_vars/all.yml
#root_password is now set in config/hailstorm_config.yml
#root_password: redhat01
ansible_host: 192.168.103.12
