---
name: rhosp-director
mem: "{{ layer2_rhosp_director_mem }}"
vcpu: "{{ layer2_rhosp_director_cpu }}"
disk:
  path: rhosp-director.qcow2
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 4096
    home: 2048
    root: 20000
nic:
  - ip: 192.168.101.30
    dev: eth0
    network: rhosp_provisioning
    default_route: false
  - ip: 192.168.100.30
    dev: eth1
    network: default
    default_route: true
  - ip: 192.168.103.30
    dev: eth2
    network: admin
    default_route: false
#hostname is now set in group_vars/all.yml
#hostname: rhosp-director.example.com
#root_password is now set in config/hailstorm_config.yml
#root_password: redhat01
ansible_host: 192.168.103.30

repos: "{{ rhosp_repos }}"

packages: python-rdomanager-oscplugin
disable_services:
  - NetworkManager

image_path: /home/stack/images
tripleo_template_path: /home/stack/my_templates

ironic_rpc_timeout: 600
nova_rpc_timeout: 600
