---
name: satellite
mem: 4096
vcpu: 2
disk:
  path: satellite.qcow2
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 4096
    home: 2048
    root: 20000
nic:
  - ip: 192.168.100.20
    dev: eth0
    network: default
    default_route: true
  - ip: 192.168.103.20
    dev: eth1
    network: admin
    default_route: false
hostname: satellite.example.com
root_password: redhat01
ansible_host: 192.168.103.20
