---
name: satellite
mem: 4096
vcpu: 2
disk:
  path: satellite.qcow2
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 4096
    home: 2048
    root: 20000
nic:
  - ip: 192.168.100.20
    dev: eth0
    network: default
    default_route: true
  - ip: 192.168.103.20
    dev: eth1
    network: admin
    default_route: false
hostname: satellite.example.com
root_password: redhat01
ansible_host: 192.168.103.20
manifestfile: manifest.zip
ntpserver: ntp.example.com

# poolid: 8a85f9814f220b7c014f2211095208d2
poolid: 8a85f9814f220b7c014f2211095208d2
repos:
  - rhel-7-server-rpms
  - rhel-server-rhscl-7-rpms
  - rhel-7-server-satellite-6.1-rpms

firewalld_rules:
 - DNStcp:
   port: 53
   protocol: udp
   state: enabled
   zone: internal
   permanent: true
 - DNSudp:
   port: 53
   protocol: udp
   state: enabled
   zone: internal
   permanent: true
 - dhcpsrv:
   port: 67
   protocol: udp
   state: enabled
   zone: internal
   permanent: true
 - dhcpcli:
   port: 68
   protocol: udp
   state: enabled
   zone: internal
   permanent: true
 - tftp:
   port: 69
   protocol: udp
   state: enabled
   zone: internal
   permanent: true
 - http:
   port: 80
   protocol: tcp
   state: enabled
   zone: internal
   permanent: true
 - https:
   port: 443
   protocol: tcp
   state: enabled
   zone: internal
   permanent: true
 - gofer:
   port: 5647
   protocol: tcp
   state: enabled
   zone: internal
   permanent: true
 - AMQP:
   port: 5671
   protocol: tcp
   state: enabled
   zone: internal
   permanent: true
 - puppet:
   port: 8140
   protocol: tcp
   state: enabled
   zone: internal
   permanent: true
