---
name: satellite
mem: "{{ layer2_satellite_mem }}"
vcpu: "{{ layer2_satellite_cpu }}"
disk:
  path: satellite.qcow2
  size: 200
  format: qcow2
  partition_table:
    lvmpv: 199500
    swap: 4096
    home: 2048
    root: 190000
nic:
  - ip: 192.168.100.20
    dev: eth0
    network: default
    default_route: true
  - ip: 192.168.103.20
    dev: eth1
    network: admin
    default_route: false
#hostname is now set in group_vars/all.yml
#hostname: satellite.example.com
#root_password is now set in config/hailstorm_config.yml
#root_password: redhat01
ansible_host: 192.168.103.20

poolid: "{{ satellite_subscription_poolid }}"
#poolid: 8a85f9814f220b7c014f2211095208d2
#poolid: 8a85f9863f14fed3013f82b2c7b33615
repos: "{{ satellite_repos }}"

packages: katello,bind-utils

firewalld_rules:
 - DNStcp:
   port: 53
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - DNSudp:
   port: 53
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - dhcpsrv:
   port: 67
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - dhcpcli:
   port: 68
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - tftp:
   port: 69
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - http:
   port: 80
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - https:
   port: 443
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - gofer:
   port: 5647
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - AMQP:
   port: 5671
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - puppet:
   port: 8140
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
