- block:
    - include: prepare_host.yml
    - include: chrony_config.yml
      when: ntp_client == 'chrony'
  when: mode=="create"

- block:
    - name: unsubscribe VM
      redhat_subscription: state=absent
      ignore_errors: yes
  when: mode=="destroy"
