- name: create content views
  command: 'hammer content-view create --name="cv-os-rhel-7-server" --organization "Default Organization"'

- name: list repo ID
  shell: 'hammer repository list --organization "Default Organization" |grep "Red Hat Enterprise Linux 7" |cut -b 1-2 '
  register: command_result

- name: add repo to content view
  shell: 'hammer content-view add-repository --name="cv-os-rhel-7-server" --organization "Default Organization" --repository-id={{ item }}'
  with_items: "{{command_result.stdout_lines}}"

- name: publish the content view
  command: 'hammer content-view publish --name="cv-os-rhel-7-server" --organization "Default Organization" --async'

- name: promote the content view to every stage
  command: 'hammer content-view version promote --organization "Default Organization" --content-view "cv-os-rhel-7-server" --to-lifecycle-environment DEV'
  command: 'hammer content-view version promote --organization "Default Organization" --content-view "cv-os-rhel-7-server" --to-lifecycle-environment TEST'
  command: 'hammer content-view version promote --organization "Default Organization" --content-view "cv-os-rhel-7-server" --to-lifecycle-environment PROD'
