- block:
    - include: install-satellite6.yml
      tags: ['install']
    - include: import_manifest.yml
      tags: ['manifest']
    - include: enable_repo_and_sync.yml
      tags: ['sync']
    - include: wait-for-sync-tasks.yml
      tags: ['wait']
    - include: lifecycle-environments.yml
      tags: ['lifecycle']
    - include: content_views.yml
      tags: ['cv']
    - include: publish_and_promote_cv.yml
      tags: ['publish']
    - include: host-collections.yml
      tags: ['hc']
    - include: sync_plan.yml
      tags: ['sp']
  when: mode=="create"

- block:
    # must happen after CV is promoted into LC envs
    - include: activation_keys.yml
      tags: ['ak']
  when: mode=="create" or mode=="refresh_subscriptions"
