---
- name: get list of vms
  virt: command=list_vms
  register: virt_vms
- name: delete kickstart files
  file: path={{ kickstart_path }}/{{ item.name }}.cfg  state=absent
  when: item.name in virt_vms.list_vms
  with_items: vms
- name: destroy vms
  virt: command=destroy name={{ item.name }}
  when: item.name in virt_vms.list_vms
  with_items: vms
- name: undefine vms
  virt: command=undefine name={{ item.name }}
  when: item.name in virt_vms.list_vms
  with_items: vms
- name: remove vm volumes
  command: virsh vol-delete {{ item.disk.path }} --pool {{ storage_default.name }}
  when: item.name in virt_vms.list_vms
  with_items: vms
