# prepare  exports
- name: create export directory
  file: state=directory path={{ item.path }}
  with_items: "{{ items }}"
- name: set export directory mode
  file: mode={{ file_mode }} path={{ item.path }}
  when: file_mode is defined
  with_items: "{{ items }}"
- name: set  export directory owner
  file: owner={{ owner }} path={{ item.path }}
  when: owner is defined
  with_items: "{{ items }}"
- name: set  export directory group
  file: group={{ group }} path={{ item.path }}
  when: group is defined
  with_items: "{{ items }}"
- name: create /etc/exports entry
  lineinfile: dest=/etc/exports regexp="{{ item.path }}.*" line="{{ item.path }} {{ infrastructure_network_storage.default_gw_host_prefix }}{{ export_params }}"
  register: etc_exports
  with_items: "{{ items }}"
- name: export file systems
  command: exportfs -a
  when: etc_exports|changed
