---
mem: "{{ layer2_ose3node_mem }}"
vcpu: "{{ layer2_ose3node_cpu }}"

disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 60
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 2048
    home: 2048
    root: 10000
