- name: Creates scripts dir
  file: path=/root/bin state=directory

- name: copy the new hv script over
  template: src=files/new-hv.py dest=/root/bin/new-hv.py mode="0755"

- name: copy the host script over
  template: src=files/check-host.py dest=/root/bin/check-host.py mode="0755"

- name: check if rhevh1 is already there
  shell: /root/bin/check-host.py rhevh1.example.com
  register: result

- name: Adding rhevh1
  command: /root/bin/new-hv.py rhevh1.example.com 192.168.103.11 255.255.255.0 192.168.100.1
  when: result.stdout != "found"

- name: check if rhevh2 is already there
  shell: /root/bin/check-host.py rhevh2.example.com
  register: result

- name: Adding rhevh2
  command: /root/bin/new-hv.py rhevh2.example.com 192.168.103.12 255.255.255.0 192.168.100.1
  when: result.stdout != "found"
