- name: get image list (default project)
  shell: >
    . ~/overcloudrc_v3 &&
    openstack image list -c Name | awk 'NR>3 { print $2 }'
  become: yes
  become_user: "{{ rhosp_stack_user }}"
  register: images
  changed_when: false
- name: load CirrOS image (default project)
  shell: >
    . ~/overcloudrc_v3 &&
    curl http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img |
    openstack image create --public --disk-format qcow2 CirrOS
  become: yes
  become_user: "{{ rhosp_stack_user }}"
  when: '"CirrOS" not in images.stdout_lines'


# - name: get image facts
#   os_image_facts:
#     auth: "{{ os_auth }}"
#     image: "{{ item.name }}"
#   register: os_image_facts
#   with_items:
#     - name: CirrOS
#
# - debug: var=os_image_facts
