- name: get image list
  shell: . ~/overcloudrc && openstack image list -c Name | awk 'NR>3 { print $2 }'
  become: yes
  become_user: "{{ rhosp_stack_user }}"
  register: images
  changed_when: false
- name: load CirrOS image
  shell: . ~/overcloudrc && curl http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img | openstack image create --public --disk-format qcow2 CirrOS
  become: yes
  become_user: "{{ rhosp_stack_user }}"
  when: '"CirrOS" not in images.stdout_lines'
