---
- block:
    - name: check if epel is installed
      shell: rpm -q epel-release
      changed_when: false
      ignore_errors: true
      register: epel

    - name: install epel-release
      command: yum -y localinstall {{ epel_rpm }}
      when: epel|failed

    - debug: msg="not implemented yet"
  when: mode=="create"


- block:
    - debug: msg="not implemented yet"
  when: mode=="destroy"
