# This is to make the various roles the layer1 host plays obvious
# layer1 roles used for delegation - here we use the host name and let ansible resolve the connection info through the inventory
infrastructure_delegate_host_used_to_test_if_layer2_host_is_available: "layer1"
infrastructure_delegate_nfs_server: "layer1"
infrastructure_delegate_kvm_host: "layer1"
infrastructure_delegate_rhel7_host_used_to_perform_xpath_select_on_curl_results: "layer1"
infrastructure_delegate_local_content_host: "layer1"
#the following hosts are not used for delegation, but used directly 
infrastructure_address_ssh_jump_host: "{{ layer1_ansible_host }}"
infrastructure_address_ntp_server: "{{ layer1_ansible_host }}"


infrastructure_network_default:
  name: 'default'
  bridge: 'virbr0'
  forward_mode: 'nat'
  host_prefix: 192.168.100.1/24
  dhcp_start: 192.168.100.128
  dhcp_end: 192.168.100.172
  floating_start: 192.168.100.173
  floating_end: 192.168.100.254

infrastructure_network_rhosp_provisioning:
  name: 'rhosp_provisioning'
  bridge: 'virbr1'
  forward_mode: 'nat'
  host_prefix: 192.168.101.1/24

infrastructure_network_storage:
  name: 'storage'
  bridge: 'virbr2'
  host_prefix: 192.168.102.1/24

infrastructure_network_admin:
  name: 'admin'
  bridge: 'virbr3'
  host_prefix: 192.168.103.1/24
  dhcp_start: 192.168.103.173
  dhcp_end: 192.168.103.254

infrastructure_network_rhosp_internal:
  name: 'rhosp_internal'
  bridge: 'virbr4'
  host_prefix: 192.168.104.1/24

infrastructure_networks:
  - "{{ infrastructure_network_default }}"
  - "{{ infrastructure_network_rhosp_provisioning }}"
  - "{{ infrastructure_network_storage }}"
  - "{{ infrastructure_network_admin }}"
  - "{{ infrastructure_network_rhosp_internal }}"
