- name: check IPA is available
  wait_for: host={{ inventory_hostname }} port=22 timeout=1
  register: ipa_available

- name: copy certificate of IPA
  command: cat /etc/ipa/ca.crt
  delegate_to: ipa
  register: certificate
  changed_when: false
  failed_when: certificate.stdout == ''
  when: ipa_available|success

- name: ensure that /etc/origin/master directory exists
  file: dest=/etc/origin/master state=directory

- name: create the cert on the OSE installer
  copy: content="{{ certificate.stdout }}" dest=/etc/origin/master/ipa-ca.crt
  when: ipa_available|success

- name: create /etc/ansible/hosts
  template: src=hosts.j2 dest=/etc/ansible/hosts
  register: ansible_hosts
- name: run installer playbook
  shell: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
  when: ansible_hosts|changed
  tags: ['playbook']
