- block:
    - include: prereqs.yml
      tags: ["ose3-prereqs"]
    - include: install.yml
      tags: ["ose3-ansible"]
    - include: register_pvs.yml
    - include: deploy_containers.yml
  when: mode=="create"
