- name: reboot server
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
- name: waiting for server to come back
  wait_for: host={{ ansible_host }} port=22 delay=30 timeout=300
  delegate_to: 10.211.55.33
