# Install RH SSO
# Author: Daniel Fröhlich
# See: https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.1/html/server_installation_and_configuration_guide/
- name: install rhsso pre-req packages
  yum:
    name: java-1.8.0-openjdk,zip,postgresql,postgresql-jdbc
    state: present

- name: enable rhsso repos
  shell: subscription-manager repos --enable=jb-eap-7.0-for-rhel-7-server-rpms --enable=rh-sso-7.1-for-rhel-7-server-rpms

- name: install rhsso group
  yum:
    name: "@rh-sso7"
    state: present

- name: create sso admin username
  shell: /opt/rh/rh-sso7/root/usr/share/keycloak/bin/add-user-keycloak.sh -r master -u admin -p {{ root_password }}
