- name: check management-infra project
  command: "oc get project {{ ose_management_infra_project }}"
  failed_when: false
  changed_when: false
  register: ose_project
- name: Create management-infra project
  command: oc new-project {{ ose_management_infra_project }} --description="Management Infrastructure"
  when: ose_project.stdout == ""
- name: check management-admin service account
  command: "oc get sa {{ ose_cfme_serviceaccount_name }} -n {{ ose_management_infra_project }}"
  failed_when: false
  changed_when: false
  register: ose_serviceaccount
- block:
  - name: Create cfme service account
    shell: "echo '{\"apiVersion\": \"v1\",\"kind\": \"ServiceAccount\",\"metadata\": {\"name\": \"{{ ose_cfme_serviceaccount_name }}\"} }' | oc create -f - -n {{ ose_management_infra_project }}"
  when: ose_serviceaccount.stdout == ""
- name: Give the cfme service account cluster-admin role.
  command: "oadm policy add-cluster-role-to-user cluster-admin system:serviceaccount:{{ ose_management_infra_project }}:{{ ose_cfme_serviceaccount_name }}"
