- name: retrieve cfme serviceaccount token name
  shell: "oc get sa {{ ose_cfme_serviceaccount_name }} -n {{ ose_management_infra_project }} -o yaml | awk '/- name:.*token.*/{ print $3 }'"
  register: token_name
  failed_when: token_name.stdout == ""
  changed_when: false
- name: retrieve cfme serviceaccount token
  shell: "oc describe secret {{ token_name.stdout }} -n {{ ose_management_infra_project }} | awk '/token:/{ print $2 }'"
  register: token_contents
  failed_when: token_contents.stdout == ""
  changed_when: false
- name: store cfme serviceaccount token as fact
  set_fact:
    ose_cmfe_token: "{{ token_contents.stdout }}"
