---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - set_fact:
        rhsm_username: "{{ rhsm_username }}"
        rhsm_password: "{{ rhsm_password }}"
      tags:
        - layer1
        - openshiftv3
        - satellite
        - rhosp
  vars_prompt:
    - name: "rhsm_username"
      prompt: "what is your Red Hat Subscription Manager username?"
#      default: "wrichter"
      default: "bhaubeck@redhat.com"
    - name: "rhsm_password"
      prompt: "what is your Red Hat Subscription Manager password?"

- hosts: layer1
  remote_user: root
  roles:
    - role: layer1
      tags: [ 'layer1' ]
      mode: create

- hosts: layer1
  remote_user: root
  roles:
    - role: layer1_vms
      tags: [ 'layer2','openshiftv3','vm' ]
      mode: create
      group: ose3-node
    - role: layer1_vms
      tags: [ 'layer2','satellite','vm' ]
      mode: create
      group: satellite
    - role: layer1_vms
      tags: [ 'layer2','rhosp', 'vm' ]
      mode: create
      group: rhosp-all

- hosts: ose3-node
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2','openshiftv3' ]
  roles:
    - { role: layer2_rhel, tags: [ 'layer2','openshiftv3', 'rhel' ], mode: create }
    - { role: layer2_openshiftv3_node, tags: [ 'layer2','openshiftv3' ], mode: create }

- hosts: satellite
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2','satellite' ]
  roles:
    - { role: layer2_rhel, tags: [ 'layer2','satellite', 'rhel' ], mode: create }
    - { role: layer2_satellite, tags: [ 'layer2','satellite' ], mode: create }

- hosts: rhosp-director
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2','rhosp', 'undercloud', 'overcloud' ]
  roles:
    - { role: layer2_rhel, tags: [ 'layer2', 'rhosp', 'rhel'], mode: create }
    - { role: layer2_rhosp_director, tags: ['layer2', 'rhosp', 'undercloud'], mode: create }
    - { role: layer2_rhosp_overcloud, tags: ['layer2', 'rhosp', 'overcloud'], mode: create }
#    - { role: layer2_rhosp_gather_node_uuids, tags: ['layer2', 'rhosp', 'overcloud'], mode: create }
