---
- hosts: layer1
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer1', 'rhosp' ]
  roles:
    - role: layer1_rhosp
      tags: [ 'rhosp', layer1 ]
      mode: create

- hosts: rhosp-all
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'rhosp', 'vm' ], mode: create }

- hosts: rhosp-director
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'rhosp', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer2', 'rhosp', 'rhel'], mode: create }
    #- { role: layer2_ipa_certificate, tags: ['layer2', 'rhosp', 'undercloud', 'undercloud-cert'], mode: create, certcn: 'director.{{ hailstorm_dns_domain }}', when: "current_lifecycle_env.openstack_version >= 10" }
    - { role: layer2_rhosp_director, tags: ['layer2', 'rhosp', 'undercloud' ], mode: create }
    #- { role: layer2_ipa_certificate, tags: ['layer2', 'rhosp', 'overcloud', 'overcloud-cert'], mode: create, certcn: 'openstack.{{ hailstorm_dns_domain }}' }
    - { role: layer2_rhosp_overcloud, tags: ['layer2', 'rhosp', 'overcloud'], mode: create }



# - hosts: lookbusy-osp
#   remote_user: root
#   gather_facts: false
#   roles:
#     - { role: layer3_vm_on_openstack, tags: [ 'layer3', 'lookbusy', 'lookbusy-osp', 'vm'], mode: create }
#     - { role: layer2_rhel, tags: [ 'layer3', 'lookbusy', 'lookbusy-osp', 'rhel'], mode: create }
#     - { role: layer3_lookbusy, tags: [ 'layer3', 'lookbusy', 'lookbusy-osp' ], mode: create }
