---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - set_fact:
        rhsm_username: "{{ rhsm_username }}"
        rhsm_password: "{{ rhsm_password }}"
      tags:
        - always
  vars_prompt:
    - name: "rhsm_username"
      prompt: "what is your Red Hat Subscription Manager username?"
      default: "wrichter"
      private: no
    - name: "rhsm_password"
      prompt: "what is your Red Hat Subscription Manager password?"

- hosts: layer1
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer1','rhosp', 'rhev' ]
  roles:
    - role: layer1
      tags: [ 'layer1' ]
      mode: create
    - role: layer1_rhosp
      tags: [ 'rhosp', layer1 ]
      mode: create
    - role: layer1_rhev
      tags: [ 'rhev', layer1 ]
      mode: create
    #- role: layer1_vms
    #  tags: [ 'layer2','satellite','vm' ]
    #  mode: create
    #  group: satellite
    #- role: layer1_vms
    #  tags: [ 'layer2','rhosp', 'vm' ]
    #  mode: create
    #  group: rhosp-all
    # - role: layer1_vms
    #   tags: [ 'layer2','rhev', 'vm' ]
    #   mode: create
    #   group: rhev


#### SATELLITE ####

- hosts: satellite
  remote_user: root
  gather_facts: false
  #pre_tasks:
  #  - setup:
  #    tags: [ 'layer2','satellite' ]
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'satellite', 'vm' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2','satellite', 'rhel' ], mode: create }
    - { role: layer2_rhel_firewalld, tags: [ 'layer2','satellite', 'rhel' ], mode: create }
    - { role: layer2_satellite, tags: [ 'layer2','satellite' ], mode: create }

- hosts: test-rhel
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'satellite', 'vm', 'test-rhel' ], mode: create }
    - { role: layer2_rhel_configure_resolv_conf, tags: [ 'layer2', 'satellite', 'res', 'test-rhel' ], mode: create, nameserver: 192.168.100.23 }
    - { role: layer2_rhel_register_with_satellite, tags: [ 'layer2', 'satellite', 'reg', 'test-rhel' ], mode: create }

#### IPA ####

- hosts: ipa
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'ipa', 'vm' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2', 'ipa', 'rhel' ], mode: create }
    - { role: layer2_rhel_firewalld, tags: [ 'layer2', 'ipa', 'rhel' ], mode: create }
    - { role: layer2_ipa, tags: [ 'layer2', 'ipa' ], mode: create }

#### Infrastructure (DNS, SMTP/IMAP) ####

- hosts: infrastructure
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'infrastructure', 'vm' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2', 'infrastructure', 'rhel' ], mode: create }
    - { role: layer2_infrastructure, tags: [ 'layer2', 'infrastructure' ], mode: create }

#### RHEV ####

- hosts: rhev
  remote_user: root
  gather_facts: false
  # pre_tasks:
  #   - setup:
  #     tags: [ 'layer2', 'rhev' ]
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'rhev', 'vm' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2', 'rhev', 'rhel' ], mode: create }
    - { role: layer2_rhel_configure_resolv_conf, tags: [ 'layer2', 'rhev' ], mode: create, nameserver: 192.168.100.23 }

- hosts: rhevm
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2', 'rhev' ]
  roles:
    - { role: layer2_rhevm_engine, tags: [ 'layer2', 'rhev', 'rhevm' ], mode: create }

- hosts: rhevh
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2', 'rhev' ]
  roles:
    - { role: layer2_rhevh, tags: [ 'layer2', 'rhev', 'rhevh' ], mode: create }

- hosts: rhevm
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2', 'rhev','rhevm-ldap' ]
  roles:
    - { role: layer2_rhevm_storage, tags: [ 'layer2', 'rhev', 'rhevm' ], mode: create }
    - { role: layer2_rhevm_ldap, tags: [ 'rhevm-ldap' ], mode: create }


#### CLOUDFORMS ####
- hosts: rhevm
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer3_cloudforms_rhev, tags: [ 'layer3', 'cf' ], mode: create }

#### OPENSTACK ####

- hosts: rhosp-all
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'rhosp', 'vm' ], mode: create }

- hosts: rhosp-director
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_rhel, tags: [ 'layer2', 'rhosp', 'rhel'], mode: create }
    - { role: layer2_rhosp_director, tags: ['layer2', 'rhosp', 'undercloud' ], mode: create }
    - { role: layer2_rhosp_overcloud, tags: ['layer2', 'rhosp', 'overcloud'], mode: create }
#    - { role: layer2_rhosp_gather_node_uuids, tags: ['layer2', 'rhosp', 'overcloud'], mode: create }
