- name: check if anyuid scc is assigned
  shell: oc get scc anyuid -o yaml
  register: anyuid
  failed_when: anyuid.stdout == ""
  changed_when: false
  delegate_to: "{{ groups['ose3-installer'][0] }}"

- block:
    - name: get current project
      shell: oc project -q
      register: current_project
      failed_when: current_project.stdout==""
      changed_when: false

    - name: change current project
      shell: oc project {{ redhat_msa_project }}
      when: current_project.stdout != redhat_msa_project

    - name: granting anyuid scc to project default user
      shell: oadm policy add-scc-to-user anyuid -z default

    - name: change current project back
      shell: oc project {{ current_project.stdout }}
      when: current_project.stdout != redhat_msa_project

  delegate_to: "{{ groups['ose3-installer'][0] }}"
  when: "'system:serviceaccount:{{ redhat_msa_project }}:default' not in (anyuid.stdout|from_yaml)['users']"
