- block:
    - name: find running VM
      shell: virsh list --name | grep "{{ name }}"
      register: virt_vms
    - name: shut down VM (gracefully)
      virt: name="{{ name }}" state=shutdown uri=qemu:///system
      when: virt_vms.stdout == "{{ name }}"
    - name: wait for VM to stop
      shell: virsh list --name | grep "{{ name }}"
      register: virt_vms
      until: virt_vms.stdout == ""
      changed_when: false
      retries: 30
      delay: 10
    #- name: force VM shutdown
    #  virsh: command=destroy name="{{ name }}"
  delegate_to: "{{ infrastructure_delegate_kvm_host }}"
