- block:
    - name: delete ironic nodes
      shell: . ~/stackrc && for i in $(ironic node-list | grep -v UUID | awk ' { print $2 } '); do ironic node-delete $i; done
    - name: delete instackenv.json file
      file: path=~/instackenv.json state=absent
  become: yes
  become_user: "{{ rhosp_stack_user }}"
